#!/usr/bin/env python3
"""Write CANONICAL.yaml for a Pass B dataset folder: one run per unit.

A unit that had to be re-run exists as <unit>, <unit>__2, ... . The canonical
run is the highest-suffixed one with a complete stream (1000 frames). Runs
that are not canonical are listed with their frame count so nobody analyses
them by accident. Hand-written notes in an existing CANONICAL.yaml are kept.

    python3 scripts/write_canonical.py data/20260911_VBTSresolution_dataset/DIGIT/20260908_passB_ball8
"""
import re, sys, glob, os, yaml, csv

folder = sys.argv[1]
prefix = os.path.basename(os.path.dirname(folder.rstrip("/"))) + "_"
runs = {}
for d in sorted(glob.glob(os.path.join(folder, prefix + "*"))):
    if not os.path.isdir(d):
        continue
    name = os.path.basename(d)
    unit = re.sub(r"__\d+$", "", name)
    f = os.path.join(d, "stream", "frames.csv")
    n = sum(1 for _ in open(f)) - 1 if os.path.exists(f) else 0
    runs.setdefault(unit, []).append((name, n))
old = {}
p = os.path.join(folder, "CANONICAL.yaml")
if os.path.exists(p):
    old = (yaml.safe_load(open(p)) or {}).get("canonical", {}) or {}
out = {}
for unit, lst in sorted(runs.items()):
    full = [x for x in lst if x[1] >= 1000]
    pick = sorted(full, key=lambda x: int((re.search(r"__(\d+)$", x[0]) or [0, 0])[1]))[-1][0] if full else None
    ent = {"run": pick} if pick else {"run": None, "note": "no complete run"}
    others = [f"{x[0]} ({x[1]} frames)" for x in lst if x[0] != pick]
    if others:
        ent["not_data"] = others
    if unit in old and isinstance(old[unit], dict) and old[unit].get("note"):
        ent["note"] = old[unit]["note"]
    d = os.path.join(folder, pick) if pick else None
    if d:
        ent["reference"] = ("reference_collect.png" if os.path.exists(os.path.join(d, "reference_collect.png"))
                            else "reference_working.png" if os.path.exists(os.path.join(d, "reference_working.png"))
                            else "reference.png (probe far away -- 8-14 % bright on DIGIT)")
    out[unit] = ent
header = ("# One run per unit for this Pass B folder. Generated by scripts/write_canonical.py;\n"
          "# re-run it after the last unit. 'not_data' runs are aborted or superseded.\n"
          "# 'reference' says which reference image analyses should difference against\n"
          "# (campaign_protocol.md 4.7 (10)).\n")
with open(p, "w") as fh:
    fh.write(header)
    yaml.safe_dump({"canonical": out}, fh, allow_unicode=True, sort_keys=False, width=200)
n_ok = sum(1 for v in out.values() if v.get("run"))
print(f"  {p}: {len(out)} units, {n_ok} with a complete run")
for u, v in out.items():
    if v.get("not_data") or not v.get("run"):
        print(f"    {u}: run={v.get('run')}  not_data={v.get('not_data')}")
